services:
  api:
    container_name: banter-api
    build: 
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis

  web:
    container_name: banter-web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api

  mongo:
    image: mongo:7
    container_name: banter-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: banter-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: